name: Test workflow

on:
  workflow_dispatch:

jobs:
  test-multi-account:
    uses: liamfit/workflow-library/.github/workflows/terraform-plan-and-apply.yml@main
    with:
      environment: dev
      terraform-version: 1.3.6
      working-directory: environments/dev
    secrets: inherit
